% ADJUST

% routine to adjust a modified JONSWAP model to the measured spectrum

% This routine fits the spectra by a modified JONSWAP spectrum in the high and low frequency bands (sea and swell) and applies criteria for distinguishing the peaks. The fitting spectrum is called modified JONSWAP because it doesn't set the spectrum decay as a function of the power of -5, but calculates the decay for each spectrum. The two peaks of higher energy are then adjusted. If the third peak of energy is the sea the routine adjusts it too, but only in this case. This technique is freely adapted from the one proposed by McCarthy T. J. 1989 "Spectral fitting procedures for Double peaked wave spectra" in: Dock and Harbour Engineering Conference, India.


% N Violante-Carvalho
% march 2000

% adapted from N Violante-Carvalho 1998

% modifications september 2000
% a new routine identpeak.m was inserted to identify if the spectrum is double peaked based on the 90% confidence interval 
% the distance from the spectral peaks is now set to 2*deltaf=0.0312Hz

% Structure

%  (1)  | select and count the peaks
%       |

%  (1?) | number of peaks
%       | 1             go to (4)
%       | 2, 3 or more  go to (2)

%  (2)  | sort the peaks
%       | max number of peaks is set as 3

%  (2?) | number of peaks
%       | 2 go to (4a?)
%       | 3 go to (3?)

%  (3?) | is the 3rd peak sea and is this peak consistent and are the peaks 2*deltaf (~0.0312Hz) apart
%       | yes go to (3)
%       | no  eliminate the 3rd peak and go to (4a?)

%  (3)  | adjust the sea
%       | 

%  (4a?)| is the 2nd peak consistent
%       | yes go to (4)
%       | no  eliminate 2nd peak and go to (4) 

%  (4)  | adjust high frequency
%       |

%  (4?) | >= 2 peaks and the peaks are 2*deltaf (~0.0312Hz) apart
%       | yes go to (5)
%       | no  go to (6)

%  (5)  | adjust low frequency
%       |  

%  (6)  | end
%       |


%  IN : C11 the power spectrum

% OUT : ah, al, as  decay from high freq, low freq and sea
%       fph, fpl, fpsea peak freq from high freq, low freq and sea
%       alfah, alfal and alfas parameter alpha from high freq, low freq and sea
%       gamah, gamal and gamas parameter gama from high freq, low freq and sea
%       kh, kl, ks parameter k from high freq, low freq and sea
%       Hshf, Hslf, Hssea significant wave height from high freq, low freq and sea
%       qual adjust quality parameter
%       m0hf, m0lf, m0sea spectral moment (order 0) from high freq, low freq and sea
%       Shf, Slf, Ssea adjusted spectra from high freq, low freq and sea


% Should we go?


np=length(C11);
f=1:np;
f=f';
f=((f*0.5)/np);

df=(npsd/nsamp)*2; %degrees of freedom
deltaf=((df/2)/(1*npsd));
delf=deltaf/16; % rate between deltaf from C11 and delf from 's' (the energy spec from the function spectrum of matlab).

% routine to select and count the number of peaks of the power spectrum
peaks;


as=0;alfas=0;gamas=0;ks=0;fpsea=0;Hssea=0;m0sea=0;Ssea=0;
ah=0;alfah=0;gamah=0;kh=0;fph=0;Hshf=0;m0hf=0;Shf=0;
al=0;alfal=0;gamal=0;kl=0;fplf=0;Hslf=0;m0lf=0;Slf=0;
fph=0;fpl=0;fpsea=0;

if length(fpn)>1,


% routine to sort the peaks from the lower to the higher energy
sortp;


% only the 3 greatest
if length(op) > 3,
op1=op(length(op)-2:length(op));
end


if length(op1) == 3, 


posop(1)=find(C11==op1(length(op1)));       % peak position of higher energy
posop(2)=find(C11==op1(length(op1)-1));     % 2nd higher
posop(3)=find(C11==op1(length(op1)-2));     % 3rd higher

fp1=f(posop(1));                            % peak frequency of higher energy
fp2=f(posop(2));                            % 2nd higher
fp3=f(posop(3));                            % 3rd higher



% Tests if the third peak is the sea. The model adjusts a trimodal spectrum only if the 3rd peak of energy is the sea, otherwise it adjusts only two peaks. So the question is 'is the 3rd peak sea?'. To the model if the two greatest peaks are greater than 7 seconds and the 3rd peak is between 4 and 7 seconds, then the 3rd peak is sea. It tests also if the peak is inconsistent, inconsistent here means if the rate between the greatest peak and the third one is greater than 15 times. It also tests if the peaks are 2 times the freq resolution apart and if it is accepted by the 90% confidence interval test (see routine identpeak.m for more details).

% in the data from Campos Basin with 32 degrees of freedom, deltat equal 1 sec a nd 1024 points, the freq resolution is 0.015625 (32/2 / 1*1024). so if the peaks are ~0.0312 Hz apart they have the minimum separation to be considered generated by different geophysical processes.


if fp1 > fp2,
fpa=fp1;
else
fpa=fp2;
end

sep=abs(fp3-fpa);

%           if sep/deltaf >= 3.2,   
%           if sep/deltaf >= 2,   
           if fp3>=0.1429
           if fp1&fp2<fp3
           if C11(posop(1))/C11(posop(3)) <= 15
ft1=fpa;ft2=fp3;
%identpeak; % use the confidence intervals to select the peaks or not
%           if lowerlim > upperlim
%           if trough < lowerlim2
           fpsea=fp3;



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%				THE SEA
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%========================================================

% routine DECAI
% routine to calculate the exponential decay a

fp=fpsea;strab=C11;

posfp=find(f==fp);

%x=f(posfp:posfp+(deltaf/delf)*5); % I used to get only 6 points after fp
%y=C11(posfp:posfp+(deltaf/delf)*5);

%pos1fp=find(f>=1.5*fp);pos1fp=pos1fp(1); % many times the interval 1.5fp to 3fp is not appropriate, so I'm getting the values just after the peak.
%op=strab(pos1fp);

%----------------------
% to calculate the segment between the two peaks used as the decay
i=posfp;
while (strab(i)-strab(i+1))>=0,
i=i+1;
end
posf=i;
%---------------------

if 3.0*fp < f(posf)
pos2fp=find(f>=3.0*fp);pos2fp=pos2fp(1);
else
pos2fp=posf;
end

% these are the points used to calculate the decay
%x=f(posfp+(deltaf/delf):pos2fp);
%y=strab(posfp+(deltaf/delf):pos2fp);
%x=f(posfp+fix((pos2fp-posfp)/2):pos2fp); %the points from the midlle to the end
%y=strab(posfp+fix((pos2fp-posfp)/2):pos2fp);
x=f(posfp+(2*fix((pos2fp-posfp)/5)):pos2fp); %the points from the 2/5 to the end
y=strab(posfp+(2*fix((pos2fp-posfp)/5)):pos2fp);

decai

as=a; % sea decay can be any value and NOT necessarily -4 ou -5

clear a x y a2

%========================================================


%========================================================

% routine ESTALFA
% routine to adust the parameter alpha

% alpha varies from 0.0001 to 0.01 and f from 1.37*fph to fmax

%a=-5; or a=-4
%fp=fpsea;strab=C11;a=as;
fp=fpsea;strab=C11;a=-5; % i'm setting the decay to -5 HERE
estalfa;


alfas=alfa3; % alpha from the sea
clear alfa3;

%========================================================


%========================================================

% routine ESTGAMA
% routine to adust the parameter gama

a=-5;
alfa=alfas;fp=fpsea;strab=C11;
estgama;

alfa=alfas;fp=fpsea;strab=C11;
estgama1; 

gamas=gama3; % gama from the sea
clear gama3

%========================================================


%========================================================

% routine ESTK
% routine to adust the parameter k

a=-5;
%alfa=alfas;gama=gamas;fp=fpsea;strab=C11;a=as;
alfa=alfas;gama=gamas;fp=fpsea;strab=C11;
estk;

ks=k; % k from the sea

clear k

%========================================================


%========================================================

% routine AJUSTESP
% adjust the modified JONSWAP spectrum S with the parameters calculated (alpha, gama and k)

a=-5;
%alfa=alfas;gama=gamas;fp=fpsea;k=ks;a=as;
alfa=alfas;gama=gamas;fp=fpsea;k=ks;
ajustesp;

Ssea=S; % spectrum adjusted from the sea
clear S strab;

%========================================================

% END OF THE ADJUST OF THE SEA



           else;end;  % if C11(posop(1))...
           else;end;  % if fp1&fp2<fp3
           else;end;  % if fp3>=0.1429
%           else;end;  % if sep/deltaf >= 3.2,
%           else;end;  % if sep/deltaf >= 2,
%         else;end;  % if lowerlim > upperlim
%         else;end;  % if trough < lowerlim2

% eliminates the 3rd peak
    op1=op1(2:3); % the 3rd peak is inconsistent or is not sea, so I don't care
    posop=posop(1:2);
           else;end;  % if length(op1) == 3


%---------------------------------------------------
% eliminate the 2nd peak if inconsistent

            if length(op1)  == 2,

posop(1)=find(C11==op1(length(op1)));       % peak position of higher energy
posop(2)=find(C11==op1(length(op1)-1));     % 2nd higher

if f(posop(1))>f(posop(2)),
fph=f(posop(1));fpl=f(posop(2));
else
fph=f(posop(2));fpl=f(posop(1));
end
ft1=fpl;ft2=fph;
%identpeak; % generates lowerlim, upperlim, trough and lowerlim2

% check if the peaks are 2 times the freq resolution apart
	    sep=abs(f(find(op1(2)==C11))-f(find(op1(1)==C11)));
     if sep/deltaf <= 2,
%     if sep/deltaf <= 3.2,
op1=op1(2);
posop=posop(1);
posop(1)=find(C11==op1);
fph=f(posop(1));
fpl=0;

% check if the ratio between the peaks is >= than 15
      elseif op1(2)/op1(1) >= 15,
op1=op1(2);
posop=posop(1);
posop(1)=find(C11==op1);
fph=f(posop(1));
fpl=0;


% check if it doesn't pass the confidence interval test

% first confidence interval test
%   elseif lowerlim < upperlim
%op1=op1(2);
%posop=posop(1);
%posop(1)=find(C11==op1);
%fph=f(posop(1));
%fpl=0;

% second confidence interval test
%   elseif trough > lowerlim2
%op1=op1(2);
%posop=posop(1);
%posop(1)=find(C11==op1);
%fph=f(posop(1));
%fpl=0;
   else,end


           end  % if length(op1)  == 2
%---------------------------------------------------


    if length(op1) == 2,

posop(1)=find(C11==op1(length(op1)));       % peak position of higher energy
posop(2)=find(C11==op1(length(op1)-1));     % 2nd higher

if f(posop(1))>f(posop(2)),
fph=f(posop(1));fpl=f(posop(2));
else
fph=f(posop(2));fpl=f(posop(1));
end

    end


else  % loop if length(fpn)>1
fph=fpn(1);al=0;fpl=0;gamal=0;alfal=0;kl=0;posfp(1)=find(f==fpn(1));
op1(1)=C11(posfp(1));
end



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%			HIGH FREQUENCY
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%========================================================

% routine DECAI
% routine to calculate the exponential decay a

fp=fph;strab=C11;

posfp=find(f==fp);

%----------------------
% to calculate the segment between the two peaks used as the decay
i=posfp;
while (strab(i)-strab(i+1))>=0,
i=i+1;
end
posf=i;
%---------------------

%pos1fp=find(f>=1.5*fp);pos1fp=pos1fp(1);
%op=strab(pos1fp);
if 3.0*fp < f(posf)
pos2fp=find(f>=3.0*fp);pos2fp=pos2fp(1);
else
pos2fp=posf;
end

% these are the points used to calculate the decay
%x=f(posfp+fix((pos2fp-posfp)/2):pos2fp); %the points from the midlle to the end
%y=strab(posfp+fix((pos2fp-posfp)/2):pos2fp);
%x=f(posfp*1.5:pos2fp); %using a simulated PM spectrum the space between 
%y=strab(posfp*1.5:pos2fp); %1.5fp to 3fp gives the best fit
x=f(posfp+(2*fix((pos2fp-posfp)/5)):pos2fp); %the points from the 2/5 to the end
y=strab(posfp+(2*fix((pos2fp-posfp)/5)):pos2fp);


decai;

ah=a; % high freq decay


%========================================================
% s1 is an auxiliar high freq spectrum where from f(0) to f(pos2fp) (obs. pos2fp is the last point before the ordinate of the function increases its value, ie a new peak is approaching) is the same as C11 (measured spectrum) and from f(pos2fp+1) to f(length(C11)) is extrapolated in function of the decay 'ah' (or -5 or -4) => y1=a2*x^(al, -5 or -4). This is done in order to get more reliable values of alpha. That's because alpha is calculated from 1.5*fp to 3*fp and many times this segment lies in the region of the next peak (the peak from sea).

% In the case of a spurious decay, ie <=-10, the decay is set to -10.0123. The variable 'rat' is the ratio between the original decay and the new one that is function os -10.0123. It's used to don't generate spikes in the transiction point in the function s1.


       if ah <= -10
x1=f(pos2fp+1:length(C11));y1=a2*x1.^(-10.0123);
  if y1(1) >= y(length(y))
rat=y1(1)/y(length(y));
y1=y1/rat;
  else
rat=y(length(y))/y1(1);
y1=y1*rat;
  end
ah=-10.0123;
       else
x1=f(pos2fp+1:length(C11));y1=a2*x1.^(ah);
       end


s1=zeros(length(C11),1);s1(1:pos2fp)=C11(1:pos2fp);
s1(pos2fp+1:length(C11))=y1;

clear a x y rat
%========================================================

% routine ESTALFA
% routine to adjust the parameter alpha

a=-5;
%fp=fph;strab=s1;a=ah;
fp=fph;strab=s1;a=-5;
estalfa;


alfah=alfa3; % alpha from high freq
clear alfa3;

%========================================================


%========================================================

% routine ESTGAMA
% routine to adust the parameter gama

a=-5;
alfa=alfah;fp=fph;strab=s1;
estgama;


alfa=alfah;fp=fph;strab=s1;
estgama1;

gamah=gama3; % gama from high freq
clear gama3

%========================================================


%========================================================

% routine ESTK
% routine to adust the parameter k

a=-5;
%alfa=alfah;gama=gamah;fp=fph;strab=s1;a=ah;
alfa=alfah;gama=gamah;fp=fph;strab=s1;
estk;

kh=k; % k from high freq

clear k

%========================================================


%========================================================

% routine AJUSTESP
% adjust the modified JONSWAP spectrum S with the parameters calculated (alpha, gama and k)

a=-5;
%alfa=alfah;gama=gamah;fp=fph;k=kh;a=ah;
alfa=alfah;gama=gamah;fp=fph;k=kh;
ajustesp;


Shf=S; % spectrum adjusted from the high freq spectrum
clear S strab;


%========================================================

% END OF THE ADJUST OF THE HIGH FREQ


Slf=0;
if length(op1) >= 2,   

% if there are two peaks and the peaks are 2 times the freq resolution apart, the low freq will be adjusted, otherwise the program finishes. At this point the consistency test has already been performed (separation between the peaks, the ratio between the peaks and the 90% confidence interval test).

% in the data from Campos Basin with 32 degrees of freedom, deltat equal 1 sec and 1024 points, the freq resolution is 0.015625 (32/2 / 1*1024). so if the peaks are ~0.03 Hz apart they have the minimum separation to be considered generated by different geophysical processes.


sep=abs(fph-fpl);


%if sep/deltaf >= 3.2,   
if sep/deltaf >= 2,   


Slf=C11-Shf';

% The low freq spectrum Slf is the difference between the measured spectrum C11 and the high freq spectrum Shf


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%				LOW FREQUENCY
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



%========================================================

% routine DECAI
% routine to calculate the exponential decay a


fp=fpl;strab=C11;

posfp=find(f==fp);

%----------------------
% to calculate the segment between the two peaks used as the decay
i=posfp;
while (strab(i)-strab(i+1))>=0,
i=i+1;
end
posf=i;
%---------------------

x=f(posfp:posf);
%y=Slf(posfp:posf);
y=C11(posfp:posf);

% As Slf is the difference between C11 and Shf negative values should be generated due to the non-exact match between the spectra. So this routine avoid negative values of y to perform the calculation of (log10) in decai.m

i=0;a=0;b=length(y);
for i=1:b,
if y(i)<=0;
a=a+1;
end
end
y=y(1:b-a);
x=x(1:b-a);

pos2fp=find(f==x(length(x)));
% these are the points used to calculate the decay
%x=f(posfp+fix((pos2fp-posfp)/2):pos2fp); %the points from the midlle to the end
%y=strab(posfp+fix((pos2fp-posfp)/2):pos2fp);
x=f(posfp+(2*fix((pos2fp-posfp)/5)):pos2fp); %the points from the 2/5 to the end
y=strab(posfp+(2*fix((pos2fp-posfp)/5)):pos2fp);

decai;

al=a; % low freq decay


% s1 is an auxiliar low freq spectrum where from f(0) to f(pos2fp) is the same as C11 (measured spectrum) (obs. pos2fp is the last point before the ordinate of the function increases its value, ie a new peak is approaching) and from f(pos2fp+1) to f(length(C11)) is extrapolated in function of the decay 'al' (or -5 or -4) => y1=a2*x^(al, -5 or -4). This is done to avoid fluctuations due to the subtraction of Slf=C11-Shf and in order to get more reliable values of alpha. That's because alpha is calculated from 1.5*fp to 3*fp and many times this segment lies in the region of the next peak (the peak from high freq).


% In the case of a spurious decay, ie <=-10, the decay is set to -10.0123. The variable 'rat' is the ratio between the original decay and the new one that is function os -10.0123. It's used to don't generate spikes in the transiction point in the function s1.

          if al <= -10
x1=f(pos2fp+1:length(C11));y1=a2*x1.^(-10.0123);
    if y1(1) >= y(length(y))
rat=y1(1)/y(length(y));
y1=y1/rat;
    else
rat=y(length(y))/y1(1);
y1=y1*rat;
    end
al=-10.0123;
          else
x1=f(pos2fp+1:length(C11));y1=a2*x1.^(al);
          end

s1=zeros(length(C11),1);s1(1:pos2fp)=C11(1:pos2fp);
s1(pos2fp+1:length(C11))=y1;

clear a x y i a b op;
%========================================================

% routine ESTALFA
% routine to adust the parameter alpha

a=-5;
%fp=fpl;strab=s1;a=al;
fp=fpl;strab=s1;a=-5;
estalfa;

alfal=alfa3; % alpha from the low freq

clear alfa3;


%========================================================


%========================================================

% routine ESTGAMA
% routine to adust the parameter gama

a=-5;
alfa=alfal;fp=fpl;strab=s1;
estgama;


alfa=alfal;fp=fpl;strab=s1;
estgama1;

gamal=gama3; % gama from the low freq
clear gama3

%========================================================


%========================================================

% routine ESTK
% routine to adust the parameter k

a=-5;
%alfa=alfal;gama=gamal;fp=fpl;strab=s1;a=al;
alfa=alfal;gama=gamal;fp=fpl;strab=s1;
estk;

kl=k; % k from the low freq

clear k

%========================================================



%========================================================

% routine AJUSTESP
% adjust the modified JONSWAP spectrum S with the parameters calculated (alpha, gama and k)

a=-5;
%alfa=alfal;gama=gamal;fp=fpl;strab=s1;k=kl;a=al;
alfa=alfal;gama=gamal;fp=fpl;strab=s1;k=kl;
ajustesp;

Slf=S; % spectrum adjusted from the low freq

clear S

%========================================================

%   END OF THE ADJUST OF LOW FREQUENCY


else;  % if sep/deltaf >= 3.2,
%else;  % if sep/deltaf >= 2,
al=0;alfal=0;gamal=0;kl=0;fpl=0;Slf=0;m0lf=0;
end;


else;  % if length(op1) >= 2,
al=0;alfal=0;gamal=0;kl=0;fpl=0;Slf=0;m0lf=0;
end;


% to eliminate spurious adjusts (decay <= -10)
%if al<=-10
%Slf=0;alfal=0;gamal=0;kl=0;fpl=0;
%elseif ah<=-10
%Shf=0;alfah=0;gamah=0;kh=0;fph=0;
%elseif as<=-10
%Ssea=0;alfas=0;gamas=0;ks=0;fpsea=0;
%else;end;


omega=2*pi*f;

m0=sum((omega.^0).*C11)/npsd;Hs=4.01*sqrt(m0);

m0hf=sum((omega.^0).*Shf')/npsd;Hshf=4.01*sqrt(m0hf);
m0lf=sum((omega.^0).*Slf')/npsd;Hslf=4.01*sqrt(m0lf);
m0sea=sum((omega.^0).*Ssea')/npsd;Hssea=4.01*sqrt(m0sea);

% Quality tests: (1) qual (ratio between the measured and the adjusted areas). (2) mean square error (mse)

qual=(m0hf+m0lf+m0sea)/m0; % adjust quality parameter

% Mean square error
S=Shf+Slf+Ssea;
soma=0;
for cont=1:length(C11),
Sr=(C11(cont)-S(cont))^2;
soma=soma+Sr;
end
mse=soma/length(C11);
% sum of the square errors => sse
sse=soma;
%========================================================================^M

clear g fp a k gama S strab nnn co dd dc x1 y1 posf a2 co dadf ;

% routine to calcute the wave parameters in the frequency domain
param;


%save sai0492 sai0492^M

clear a2 dadf posf s1


