-- MySQL Script generated by MySQL Workbench
-- Sex 28 Abr 2017 16:40:42 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DADOS_MET
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DADOS_MET
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DADOS_MET` DEFAULT CHARACTER SET utf8 ;
USE `DADOS_MET` ;

-- -----------------------------------------------------
-- Table `DADOS_MET`.`estacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DADOS_MET`.`estacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `stId` VARCHAR(45) NOT NULL COMMENT 'Identificação da estação',
  `nomeEstacao` VARCHAR(45) NULL COMMENT 'Nome da estação',
  `uf` VARCHAR(2) NULL COMMENT 'Unidade Federativa onde a estação está localizada',
  `cidade` VARCHAR(45) NULL COMMENT 'Cidade onde e estação está localizada',
  `latitude` DECIMAL NULL COMMENT 'Latitude da estação em grau decimal',
  `longitude` DECIMAL NULL COMMENT 'Longitude da estação em grau decimal',
  `codigoOMM` VARCHAR(45) NULL,
  `registro` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Relação das estações cadastradas no banco de dados';


-- -----------------------------------------------------
-- Table `DADOS_MET`.`dadosMeteorologicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DADOS_MET`.`dadosMeteorologicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dataHora` DATETIME NOT NULL COMMENT 'Valor de temperatura em ',
  `temperatura` DOUBLE NULL COMMENT 'Valor de umidade em ',
  `umidade` DOUBLE NULL,
  `po` DOUBLE NULL,
  `press` DOUBLE NULL,
  `pre` DOUBLE NULL,
  `rad` DOUBLE NULL,
  `vdd` DOUBLE NULL,
  `vvel` DOUBLE NULL,
  `estacoes_id` INT NOT NULL,
  PRIMARY KEY (`id`, `estacoes_id`),
  INDEX `fk_dadosMeteorologicos_estacoes_idx` (`estacoes_id` ASC),
  CONSTRAINT `fk_dadosMeteorologicos_estacoes`
    FOREIGN KEY (`estacoes_id`)
    REFERENCES `DADOS_MET`.`estacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Dados das estações';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
