% clear all; close all; clc;
% readfort345.m
% matlab program to read the spec generated by program ../sarpaper/readfort30.f
% readfort30.f extracts the partitions of the spec

% readfort345.m plots the whole partition
% 

npart=0;

%fi='/data/sudo/AVHRR/nvc/sarpaper/part/fort.245';
fi='fort.245';

fid=fopen(fi,'r');

                           % IMPORTANT stuff
dum = fseek(fid,4,'bof');  % to skip a 4-byte record mark before the data
                           % written by fortran
while ~feof(fid)

x1=fread(fid,[1,3],'double'); 
eval(['lonfg_part_' num2str(npart) ' = x1(1);' ])
eval(['latfg_part_' num2str(npart) ' = x1(2);' ])
eval(['datefg_part_' num2str(npart) ' = x1(3);' ])

x2=fread(fid,[1,2],'integer*4');
eval(['nangfg_part_' num2str(npart) ' = x2(1);' ])
eval(['nfrefg_part_' num2str(npart) ' = x2(2);' ])

x3=fread(fid,[1,3],'double');
eval(['th0fg_part_' num2str(npart) ' = x3(1);' ])
eval(['fr1fg_part_' num2str(npart) ' = x3(2);' ])
eval(['cofg_part_' num2str(npart) ' = x3(3);' ])

clear x1 x2 x3

dum=fread(fid,1,'int32');          % read the binary record length tag
dum=fread(fid,1,'int32');          % read the binary record length tag

hsfg_part=fread(fid,[1,1],'double');
eval(['hsfg_part_' num2str(npart) ' = hsfg_part;' ])
clear hsfg_part

dum=fread(fid,1,'int32');          % read the binary record length tag
dum=fread(fid,1,'int32');          % read the binary record length tag

meandirfg_part=fread(fid,[1,1],'double');
eval(['meandirfg_part_' num2str(npart) ' = meandirfg_part;' ])
clear meandirfg_part

dum=fread(fid,1,'int32');          % read the binary record length tag
dum=fread(fid,1,'int32');          % read the binary record length tag

meanffg_part=fread(fid,[1,1],'double');
eval(['meanffg_part_' num2str(npart) ' = meanffg_part;' ])
clear meanffg_part

dum=fread(fid,1,'int32');          % read the binary record length tag
dum=fread(fid,1,'int32');          % read the binary record length tag

u10fg_part=fread(fid,[1,1],'double');
eval(['u10fg_part_' num2str(npart) ' = u10fg_part;' ])
clear u10fg_part

dum=fread(fid,1,'int32');          % read the binary record length tag
dum=fread(fid,1,'int32');          % read the binary record length tag

windirfg_part=fread(fid,[1,1],'double');
eval(['windirfg_part_' num2str(npart) ' = windirfg_part;' ])
clear windirfg_part

dum=fread(fid,1,'int32');          % read the binary record length tag
dum=fread(fid,1,'int32');          % read the binary record length tag

specfg_part=fread(fid,[24,25],'double');
eval(['specfg_part_' num2str(npart) ' = specfg_part;' ])
clear specfg_part

dum=fread(fid,1,'int32');          % read the binary record length tag
dum=fread(fid,1,'int32');

npart=npart+1;

end
fclose all;